### ISSUE TITLE
Issues with streaming to the app

### ISSUE THREAD

**Issue by sgodanas** [shycats/VirtuCameraMaya#3]
Hello.

Lately we have been encountering issues. Here is a description from the artist (Windows 10, Mac OS)

`Maya is unable to sort what viewport to utilize and flickers on and off, and I have nothing on my iPad.  It's a black screen.  I also get a crossed out eye icon in the upper corner of the viewport.  I'm able to drive the camera within Maya because the one thing that is consistent is that I get a small virtuCamera port floating free and am able to adjust the camera with my iPad so the tracking it working....`

We see the following error in the script editor

```
from maya import cmds; cmds.virtuCamera()
VirtuCamera: Listening on TCP port 23354
VirtuCamera: Accepted connection from: XXX.YYY.1.241:49345
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
VirtuCamera: Ffmpeg has stopped working with return code 1
VirtuCamera: Starting Viewport Streaming. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
#   File "C:/Users/jbermudes/Documents/maya/2020/plug-ins\virtuCameraMaya\virtuCameraMaya.py", line 440, in _autosend_loop
# Traceback (most recent call last):
<bound method VirtuCameraMaya._autosend_loop of <virtuCameraMaya.virtuCameraMaya.VirtuCameraMaya object at 0x000002734DC50940>># Unhandled exception in thread started by
[Errno 10053] An established connection was aborted by the software in your host machine: error.# socketself._tcp_clt_socket.send(cmd+data)
#     #   File "C:/Users/jbermudes/Documents/maya/2020/plug-ins\virtuCameraMaya\virtuCameraMaya.py", line 359, in _tcp_send
self._tcp_send(self._CMD_ERR_NOT_STREAMING)
#     #   File "C:/Users/jbermudes/Documents/maya/2020/plug-ins\virtuCameraMaya\virtuCameraMaya.py", line 561, in _send_viewport_img
self._send_viewport_img()
#     VirtuCamera: Disconnected from: XXX.YYY.1.241:49345
VirtuCamera: Listening on TCP port 23354
VirtuCamera: Stopped serving
``` 

Any idea why this seems to happen once in a while?

Thank you,
Satish.
Netflix Animation

**Comment by shycats** [comment]
Hello Satish,

This error is usually caused by a network connectivity problem, an unstable network connection or low quality WiFi signal. 
You can try replacing the network cable if the computer is connected through ethernet. Also, placing the WiFi access point near the work area and trying with other WiFi channels may help.
Does this make sense to you?

Best,
Pablo.

**Comment by shycats** [comment]
In case this happens all the time, meaning it never worked in that computer, it's probably a firewall blocking the connection. There are two connections that needs to be allowed in the firewall:
- TCP connection from iPad incoming to Maya on port 23354
- TCP connection outgoing from Maya to iPad on port 23354

**Comment by sgodanas** [comment]
Hi Pablo, Thank you for the prompt response and that makes sense. This issue never occurred to me during my testing (I am on WIFI), so we are keeping a close eye on the environment of the artist facing the issue.

Also, Does VirtuCamera write out log files to the filesystem?

**Comment by shycats** [comment]
No, it doesn't write out log files, it only prints error messages to the script editor in Maya.

**Comment by sgodanas** [comment]
Okay, Thank you Pablo.

**Comment by sgodanas** [comment]
Hi Pablo. We checked all the things you mentioned, but the viewport is still not streaming to the app (for an user). But the camera in Maya is being synchronized with the device's movements. We are going to investigate further on our end.

Thank you.
Satish.

**Comment by sgodanas** [comment]
Hi Pablo.

Are all versions of iPadOS supported by the app? 

Thank you,
Satish.

**Comment by shycats** [comment]
Hello,

Yes, the App supports iOS 12.1 and later, which includes all iPadOS versions.
You can check supported devices at the end of this page:
[https://www.apple.com/augmented-reality/](https://www.apple.com/augmented-reality/)

**Comment by sgodanas** [comment]
Thank you Pablo.

We were able to replicate this issue with the server running on a cloud workstation. It looks like there is another port being used for transmitting the image stream and most likely a blocked port is causing the issue.

Will keep you posted.
Satish.
Netflix Animation.

**Comment by sgodanas** [comment]
This is resolved. Thank you.
