### ISSUE TITLE
Maya 2023, VCCore src missing

### ISSUE THREAD

**Issue by Dariusz1989** [shycats/VirtuCameraMaya#6]
Hey

I wanted to recompile VCCore.pyd file for new python/maya 2023, but I can't find source for it.

Can you please provide the file or compiled version so we can try it with 2023?

Regards
Dariusz

**Comment by shycats** [comment]
Hello, you can find a pre-release for Maya 2023 here
https://github.com/shycats/VirtuCameraMaya/releases/tag/v2.0.2_2023

It seems there are some issues in MacOS but otherwise it should be working fine.
Cheers!

**Comment by Dariusz1989** [comment]
Epic thanks!
